-- SLUMLINK compatibility-first migration from MySQL to Supabase PostgreSQL.
--
-- This migration intentionally preserves the current table and column names so
-- the Express API can be migrated incrementally. Binary columns remain bytea
-- for now; a later migration will move files to Supabase Storage.

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.organizations (
  org_id bigint generated by default as identity (start with 2000) primary key,
  org_type text not null default 'ngo'
    check (org_type in ('ngo', 'localauthority')),
  org_name varchar(150) not null,
  email varchar(150) not null unique,
  phone varchar(20) not null unique,
  org_age integer not null check (org_age >= 0),
  password varchar(255) not null,
  status text not null default 'pending'
    check (status in ('pending', 'accepted', 'rejected', 'suspended')),
  license_filename varchar(255) not null,
  license_mimetype varchar(100) not null,
  license_size bigint not null check (license_size >= 0),
  license_file bytea not null
);

create table public.slum_dwellers (
  id bigint generated by default as identity primary key,
  slum_code varchar(8) unique,
  password_hash varchar(255) not null,
  full_name varchar(150) not null,
  mobile varchar(20),
  nid varchar(30),
  dob date,
  gender text check (gender in ('Male', 'Female', 'Others')),
  education varchar(100),
  occupation varchar(100),
  income varchar(50),
  area varchar(150),
  district varchar(150),
  division varchar(150),
  family_members integer default 0 check (family_members >= 0),
  status text not null default 'pending'
    check (status in ('pending', 'accepted', 'rejected', 'suspended')),
  skills_1 varchar(100) default 'None',
  skills_2 varchar(100) default 'None',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.assign_slum_code()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.slum_code is null then
    new.slum_code := 'SR' || lpad(new.id::text, 6, '0');
  end if;
  return new;
end;
$$;

create trigger assign_slum_code_before_insert
before insert on public.slum_dwellers
for each row execute function public.assign_slum_code();

create trigger set_slum_dwellers_updated_at
before update on public.slum_dwellers
for each row execute function public.set_updated_at();

create table public.spouses (
  id bigint generated by default as identity primary key,
  slum_id varchar(8) references public.slum_dwellers(slum_code) on delete cascade,
  name varchar(150) not null,
  dob date,
  gender text check (gender in ('Male', 'Female', 'Others')),
  nid varchar(30),
  education varchar(100),
  job varchar(100),
  income varchar(50),
  mobile varchar(20),
  marriage_certificate bytea,
  divorce_certificate bytea,
  status text not null default 'pending_add'
    check (status in ('active', 'pending_add', 'pending_remove')),
  skills_1 varchar(100) default 'None',
  skills_2 varchar(100) default 'None',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index spouses_slum_id_idx on public.spouses (slum_id);
create index spouses_status_idx on public.spouses (status);

create trigger set_spouses_updated_at
before update on public.spouses
for each row execute function public.set_updated_at();

create table public.children (
  id bigint generated by default as identity primary key,
  slum_id varchar(8) references public.slum_dwellers(slum_code) on delete cascade,
  name varchar(150) not null,
  dob date,
  gender text check (gender in ('Male', 'Female', 'Others')),
  education varchar(100),
  job varchar(100),
  income varchar(50),
  preferred_job varchar(150),
  birth_certificate bytea,
  death_certificate bytea,
  birth_certificate_number varchar(50) unique,
  age_group text default 'child' check (age_group in ('child', 'adult')),
  status text not null default 'pending_add'
    check (status in ('active', 'pending_add', 'pending_remove')),
  skills_1 varchar(100) default 'None',
  skills_2 varchar(100) default 'None',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index children_slum_id_idx on public.children (slum_id);
create index children_status_idx on public.children (status);

create trigger set_children_updated_at
before update on public.children
for each row execute function public.set_updated_at();

create table public.documents (
  id bigint generated by default as identity primary key,
  slum_id varchar(8) not null references public.slum_dwellers(slum_code) on delete cascade,
  document_type varchar(100) not null,
  document_title varchar(150),
  file_blob bytea not null,
  file_mimetype varchar(100),
  file_size bigint check (file_size >= 0),
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected')),
  uploaded_at timestamptz not null default now(),
  reviewed_by varchar(150),
  reviewed_at timestamptz,
  rejection_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index documents_slum_status_idx on public.documents (slum_id, status);
create index documents_status_idx on public.documents (status);
create index documents_created_at_idx on public.documents (created_at);

create trigger set_documents_updated_at
before update on public.documents
for each row execute function public.set_updated_at();

create table public.complaints (
  complaint_id bigint generated by default as identity primary key,
  slum_id varchar(8) not null references public.slum_dwellers(slum_code) on delete cascade,
  title varchar(200) not null,
  category varchar(100) not null,
  description text not null,
  attachment_filename varchar(255) not null,
  attachment_mimetype varchar(100) not null,
  attachment_size bigint not null check (attachment_size >= 0),
  attachment_file bytea not null,
  division varchar(150),
  district varchar(150),
  area varchar(150),
  status text not null default 'pending'
    check (status in ('pending', 'in progress', 'resolved')),
  responded_by varchar(150),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index complaints_slum_id_idx on public.complaints (slum_id);
create index complaints_status_idx on public.complaints (status);
create index complaints_location_idx on public.complaints (division, district, area);
create index complaints_created_at_idx on public.complaints (created_at desc);

create trigger set_complaints_updated_at
before update on public.complaints
for each row execute function public.set_updated_at();

create table public.campaigns (
  campaign_id bigint generated by default as identity primary key,
  org_id bigint,
  title varchar(180) not null,
  category varchar(120) not null,
  division varchar(150) not null,
  district varchar(150) not null,
  slum_area varchar(150) not null,
  start_date date not null,
  end_date date not null,
  start_time time,
  target_gender text not null default 'all'
    check (target_gender in ('all', 'female', 'male', 'others')),
  age_group text not null check (age_group in ('child', 'adult', 'both')),
  education_required varchar(50),
  skills_required varchar(50),
  description text not null,
  status text not null default 'pending'
    check (status in ('pending', 'in_progress', 'completed', 'not_executed', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_date >= start_date)
);

create index campaigns_org_id_idx on public.campaigns (org_id);
create index campaigns_area_idx on public.campaigns (division, district, slum_area);
create index campaigns_filters_idx on public.campaigns
  (target_gender, age_group, education_required, skills_required);
create index campaigns_dates_idx on public.campaigns (start_date, end_date);
create index campaigns_status_idx on public.campaigns (status);

create trigger set_campaigns_updated_at
before update on public.campaigns
for each row execute function public.set_updated_at();

create table public.notifications (
  notification_id bigint generated by default as identity primary key,
  slum_code varchar(8) not null references public.slum_dwellers(slum_code) on delete cascade,
  campaign_id bigint not null,
  org_id bigint not null,
  type text not null
    check (type in ('campaign_created', 'campaign_updated', 'campaign_cancelled')),
  title varchar(200) not null,
  message text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create index notifications_slum_created_idx on public.notifications (slum_code, created_at desc);
create index notifications_campaign_idx on public.notifications (campaign_id);

create table public.campaign_targets (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null,
  slum_code varchar(8) not null,
  matched_at timestamptz not null default now(),
  constraint campaign_targets_campaign_slum_key unique (campaign_id, slum_code)
);

create index campaign_targets_slum_code_idx on public.campaign_targets (slum_code);

create table public.aid_types (
  aid_type_id integer generated by default as identity primary key,
  name varchar(80) not null unique,
  requires_quantity boolean not null default false,
  unit_label varchar(40)
);

insert into public.aid_types (name, requires_quantity, unit_label)
values
  ('Food', true, 'pack'),
  ('Clothing', true, 'pcs'),
  ('Medicine', true, 'pcs'),
  ('Cash', true, 'BDT'),
  ('Skill Training', false, null),
  ('Job Placement', false, null)
on conflict (name) do nothing;

create table public.distribution_sessions (
  session_id bigint generated by default as identity primary key,
  campaign_id bigint not null,
  org_id bigint not null,
  aid_type_id integer not null,
  status text not null default 'OPEN' check (status in ('OPEN', 'CLOSED')),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  performed_by varchar(150)
);

create index distribution_sessions_campaign_idx on public.distribution_sessions (campaign_id);
create index distribution_sessions_org_idx on public.distribution_sessions (org_id);
create index distribution_sessions_aid_type_idx on public.distribution_sessions (aid_type_id);

create table public.distribution_entries (
  entry_id bigint generated by default as identity primary key,
  session_id bigint not null,
  campaign_id bigint not null,
  org_id bigint not null,
  family_code varchar(8) not null,
  round_no integer not null default 1 check (round_no > 0),
  quantity integer check (quantity is null or quantity >= 0),
  comment varchar(500),
  distributed_at timestamptz not null default now(),
  verification_method text not null default 'CODE'
    check (verification_method in ('CODE', 'QR')),
  constraint distribution_entries_session_family_round_key
    unique (session_id, family_code, round_no)
);

create index distribution_entries_campaign_idx on public.distribution_entries (campaign_id);
create index distribution_entries_org_idx on public.distribution_entries (org_id);
create index distribution_entries_family_idx on public.distribution_entries (family_code);

create or replace function public.assign_distribution_round()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.round_no is null or new.round_no <= 0 then
    select coalesce(max(de.round_no), 0) + 1
      into new.round_no
      from public.distribution_entries as de
     where de.session_id = new.session_id
       and de.family_code = new.family_code;
  end if;
  return new;
end;
$$;

create trigger assign_distribution_round_before_insert
before insert on public.distribution_entries
for each row execute function public.assign_distribution_round();

create view public.vw_family_donation_history
with (security_invoker = true)
as
select
  de.family_code,
  de.distributed_at,
  de.campaign_id,
  de.org_id,
  de.quantity,
  de.verification_method,
  de.comment,
  de.round_no,
  de.session_id
from public.distribution_entries as de;

-- No browser client receives table data until explicit policies are added.
alter table public.organizations enable row level security;
alter table public.slum_dwellers enable row level security;
alter table public.spouses enable row level security;
alter table public.children enable row level security;
alter table public.documents enable row level security;
alter table public.complaints enable row level security;
alter table public.campaigns enable row level security;
alter table public.notifications enable row level security;
alter table public.campaign_targets enable row level security;
alter table public.aid_types enable row level security;
alter table public.distribution_sessions enable row level security;
alter table public.distribution_entries enable row level security;

